/* Generated by Spinel AOT compiler */
#include "sp_runtime.h"
static const char *sp_sym_to_s(sp_sym id){(void)id;return "";}

typedef struct sp_SpinelLogic_s sp_SpinelLogic;

struct sp_SpinelLogic_s {
  sp_IntArray * labels;
  sp_StrIntHash * mcc_risk;
  mrb_float max_amount;
  mrb_float max_inst;
  mrb_float avg_ratio_limit;
  mrb_float max_min;
  mrb_float max_km;
  mrb_float max_tx;
  mrb_float max_m_avg;
  mrb_float inv_max_amount;
  mrb_float inv_max_inst;
  mrb_float inv_avg_ratio_limit;
  mrb_float inv_max_min;
  mrb_float inv_max_km;
  mrb_float inv_max_tx;
  mrb_float inv_max_m_avg;
};

static void sp_SpinelLogic_gc_scan(void *p) {
  sp_SpinelLogic *self = (sp_SpinelLogic *)p;
  if (self->labels) sp_gc_mark((void *)self->labels);
  if (self->mcc_risk) sp_gc_mark((void *)self->mcc_risk);
}

static sp_SpinelLogic *sp_SpinelLogic_new(sp_IntArray * lv_labels, sp_StrIntHash * lv_mcc_risk, mrb_float lv_max_amount, mrb_float lv_max_inst, mrb_float lv_avg_ratio_limit, mrb_float lv_max_min, mrb_float lv_max_km, mrb_float lv_max_tx, mrb_float lv_max_m_avg);
static inline void sp_SpinelLogic_initialize(sp_SpinelLogic *self, sp_IntArray * lv_labels, sp_StrIntHash * lv_mcc_risk, mrb_float lv_max_amount, mrb_float lv_max_inst, mrb_float lv_avg_ratio_limit, mrb_float lv_max_min, mrb_float lv_max_km, mrb_float lv_max_tx, mrb_float lv_max_m_avg);
static sp_FloatArray * sp_SpinelLogic_build_vector(sp_SpinelLogic *self, mrb_float lv_amount, mrb_float lv_inst, mrb_float lv_cust_avg, mrb_int lv_hour, mrb_int lv_wday, mrb_float lv_last_tx_mins, mrb_float lv_last_tx_km, mrb_float lv_km_home, mrb_float lv_tx_c, mrb_bool lv_is_online, mrb_bool lv_card_present, mrb_bool lv_known_merch, const char * lv_mcc, mrb_float lv_m_avg);
static mrb_float sp_SpinelLogic_calculate_score(sp_SpinelLogic *self, sp_IntArray * lv_indices);

static inline sp_SpinelLogic *sp_SpinelLogic_new(sp_IntArray * lv_labels, sp_StrIntHash * lv_mcc_risk, mrb_float lv_max_amount, mrb_float lv_max_inst, mrb_float lv_avg_ratio_limit, mrb_float lv_max_min, mrb_float lv_max_km, mrb_float lv_max_tx, mrb_float lv_max_m_avg) {
  SP_GC_SAVE();
  sp_SpinelLogic *self = (sp_SpinelLogic *)sp_gc_alloc(sizeof(sp_SpinelLogic), NULL, sp_SpinelLogic_gc_scan);
  SP_GC_ROOT(self);
  SP_GC_ROOT(lv_labels);
  SP_GC_ROOT(lv_mcc_risk);
  self->labels = lv_labels;
  self->mcc_risk = lv_mcc_risk;
  self->max_amount = lv_max_amount;
  self->max_inst = lv_max_inst;
  self->avg_ratio_limit = lv_avg_ratio_limit;
  self->max_min = lv_max_min;
  self->max_km = lv_max_km;
  self->max_tx = lv_max_tx;
  self->max_m_avg = lv_max_m_avg;
  self->inv_max_amount = (1.0 / ((lv_max_amount > 0.0) ? lv_max_amount : 1.0));
  self->inv_max_inst = (1.0 / ((lv_max_inst > 0.0) ? lv_max_inst : 1.0));
  self->inv_avg_ratio_limit = (1.0 / ((lv_avg_ratio_limit > 0.0) ? lv_avg_ratio_limit : 1.0));
  self->inv_max_min = (1.0 / ((lv_max_min > 0.0) ? lv_max_min : 1.0));
  self->inv_max_km = (1.0 / ((lv_max_km > 0.0) ? lv_max_km : 1.0));
  self->inv_max_tx = (1.0 / ((lv_max_tx > 0.0) ? lv_max_tx : 1.0));
  self->inv_max_m_avg = (1.0 / ((lv_max_m_avg > 0.0) ? lv_max_m_avg : 1.0));
  SP_GC_RESTORE();
  return self;
}

static inline void sp_SpinelLogic_initialize(sp_SpinelLogic *self, sp_IntArray * lv_labels, sp_StrIntHash * lv_mcc_risk, mrb_float lv_max_amount, mrb_float lv_max_inst, mrb_float lv_avg_ratio_limit, mrb_float lv_max_min, mrb_float lv_max_km, mrb_float lv_max_tx, mrb_float lv_max_m_avg) {
  self->labels = lv_labels;
  self->mcc_risk = lv_mcc_risk;
  self->max_amount = lv_max_amount;
  self->max_inst = lv_max_inst;
  self->avg_ratio_limit = lv_avg_ratio_limit;
  self->max_min = lv_max_min;
  self->max_km = lv_max_km;
  self->max_tx = lv_max_tx;
  self->max_m_avg = lv_max_m_avg;
  self->inv_max_amount = (1.0 / ((lv_max_amount > 0.0) ? lv_max_amount : 1.0));
  self->inv_max_inst = (1.0 / ((lv_max_inst > 0.0) ? lv_max_inst : 1.0));
  self->inv_avg_ratio_limit = (1.0 / ((lv_avg_ratio_limit > 0.0) ? lv_avg_ratio_limit : 1.0));
  self->inv_max_min = (1.0 / ((lv_max_min > 0.0) ? lv_max_min : 1.0));
  self->inv_max_km = (1.0 / ((lv_max_km > 0.0) ? lv_max_km : 1.0));
  self->inv_max_tx = (1.0 / ((lv_max_tx > 0.0) ? lv_max_tx : 1.0));
  self->inv_max_m_avg = (1.0 / ((lv_max_m_avg > 0.0) ? lv_max_m_avg : 1.0));
}

static sp_FloatArray * sp_SpinelLogic_build_vector(sp_SpinelLogic *self, mrb_float lv_amount, mrb_float lv_inst, mrb_float lv_cust_avg, mrb_int lv_hour, mrb_int lv_wday, mrb_float lv_last_tx_mins, mrb_float lv_last_tx_km, mrb_float lv_km_home, mrb_float lv_tx_c, mrb_bool lv_is_online, mrb_bool lv_card_present, mrb_bool lv_known_merch, const char * lv_mcc, mrb_float lv_m_avg) {
    SP_GC_SAVE();
    mrb_float lv_avg_ratio = 0.0;
    sp_FloatArray * lv_v = NULL;
    mrb_int lv_risk_int = 0;
    SP_GC_ROOT(lv_v);
    SP_GC_ROOT(self);
    SP_GC_ROOT(lv_mcc);
    lv_avg_ratio = ((lv_cust_avg > 0.0) ? ((lv_amount / lv_cust_avg) * self->inv_avg_ratio_limit) : 1.0);
    sp_FloatArray *_t1 = sp_FloatArray_new();
    { mrb_int _n = 14; mrb_float _v = 0.0; for (mrb_int _i = 0; _i < _n; _i++) sp_FloatArray_push(_t1, _v); }
    lv_v = _t1;
    sp_FloatArray_set(lv_v, 0, ((lv_amount > self->max_amount) ? 1.0 : (lv_amount * self->inv_max_amount)));
    sp_FloatArray_set(lv_v, 1, ((lv_inst > self->max_inst) ? 1.0 : (lv_inst * self->inv_max_inst)));
    sp_FloatArray_set(lv_v, 2, ((lv_avg_ratio > 1.0) ? 1.0 : ((lv_avg_ratio < 0.0) ? 0.0 : lv_avg_ratio)));
    sp_FloatArray_set(lv_v, 3, ((mrb_float)(lv_hour) * (1.0 / 23.0)));
    sp_FloatArray_set(lv_v, 4, ((mrb_float)(lv_wday) * (1.0 / 6.0)));
    if ((lv_last_tx_mins >= 0.0)) {
      sp_FloatArray_set(lv_v, 5, ((lv_last_tx_mins > self->max_min) ? 1.0 : (lv_last_tx_mins * self->inv_max_min)));
      sp_FloatArray_set(lv_v, 6, ((lv_last_tx_km > self->max_km) ? 1.0 : (lv_last_tx_km * self->inv_max_km)));
    } else {
      sp_FloatArray_set(lv_v, 5, -1.0);
      sp_FloatArray_set(lv_v, 6, -1.0);
    }
    sp_FloatArray_set(lv_v, 7, ((lv_km_home > self->max_km) ? 1.0 : (lv_km_home * self->inv_max_km)));
    sp_FloatArray_set(lv_v, 8, ((lv_tx_c > self->max_tx) ? 1.0 : (lv_tx_c * self->inv_max_tx)));
    sp_FloatArray_set(lv_v, 9, (lv_is_online ? 1.0 : 0.0));
    sp_FloatArray_set(lv_v, 10, (lv_card_present ? 1.0 : 0.0));
    sp_FloatArray_set(lv_v, 11, (lv_known_merch ? 0.0 : 1.0));
    lv_risk_int = sp_StrIntHash_get(self->mcc_risk, lv_mcc);
    sp_FloatArray_set(lv_v, 12, ((lv_risk_int > 0) ? ((mrb_float)(lv_risk_int) * 0.001) : 0.5));
    sp_FloatArray_set(lv_v, 13, ((lv_m_avg > self->max_m_avg) ? 1.0 : (lv_m_avg * self->inv_max_m_avg)));
    return lv_v;
  return NULL;
}

static mrb_float sp_SpinelLogic_calculate_score(sp_SpinelLogic *self, sp_IntArray * lv_indices) {
    mrb_int lv_frauds = 0;
    mrb_int lv_i = 0;
    mrb_int lv_len = 0;
    SP_GC_SAVE();
    SP_GC_ROOT(self);
    SP_GC_ROOT(lv_indices);
    lv_frauds = 0;
    lv_i = 0;
    lv_len = sp_IntArray_length(lv_indices);
    while ((lv_i < lv_len)) {
      lv_frauds += sp_IntArray_get(self->labels, sp_IntArray_get(lv_indices, lv_i));
      lv_i += 1;
    }
    return ((mrb_float)(lv_frauds) / (mrb_float)(lv_len));
  return 0.0;
}

typedef struct{const char**data;mrb_int len;}sp_Argv;
static sp_Argv sp_argv;

int main(int argc,char**argv){
  sp_argv.len=argc-1;sp_argv.data=(const char**)malloc(sizeof(const char*)*(argc>1?argc-1:1));{int _i;for(_i=0;_i<sp_argv.len;_i++)sp_argv.data[_i]=sp_str_dup_external(argv[_i+1]);}
    SP_GC_SAVE();
    sp_IntArray *lv_labels = NULL;
    SP_GC_ROOT(lv_labels);
    sp_StrIntHash *lv_mcc_risk = NULL;
    SP_GC_ROOT(lv_mcc_risk);
    sp_SpinelLogic *lv_obj = NULL;
    SP_GC_ROOT(lv_obj);

    sp_IntArray *_t2 = sp_IntArray_new();
    sp_IntArray_push(_t2, 0);
    lv_labels = _t2;
    sp_StrIntHash *_t3 = sp_StrIntHash_new();
    sp_StrIntHash_set(_t3, (&("\xff" "5411")[1]), 150);
    lv_mcc_risk = _t3;
    lv_obj = sp_SpinelLogic_new(lv_labels, lv_mcc_risk, 10000.0, 12.0, 10.0, 1440.0, 1000.0, 20.0, 10000.0);
    sp_SpinelLogic_build_vector(lv_obj, 100.0, 1.0, 50.0, 12, 1, 10.0, 1.0, 5.0, 1.0, TRUE, TRUE, TRUE, (&("\xff" "5411")[1]), 100.0);
    sp_IntArray *_t4 = sp_IntArray_new();
    sp_IntArray_push(_t4, 0);
    sp_SpinelLogic_calculate_score(lv_obj, _t4);
  return 0;
}
